[package]
name = "containerfile-parser"
version = "0.1.0"
edition = "2021"
authors = ["github.com/navidys/containerfile-parser"]
license = "MIT"
readme = "README.md"
description = "Rust library for parsing, validating, and modifying Containerfile/Dockerfile"

[dependencies]
